Repository puppetlabs/puppetlabs-pe_databases, pull requests merged in 2021-06, with the labels that each got.

#58 Update to latest stable PDK template
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .fixtures.yml
  .pdkignore
  .rubocop.yml
  .sync.yml
  Gemfile
  Rakefile
  metadata.json
Labels: maintenance

#63 PE acceptance workflows and Idempotency Test
  .fixtures.yml
  .github/workflows/pe_latest_testing.yml
  .github/workflows/pe_lts_testing.yml
  spec/acceptance/init_spec.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#65 SUP-2404 systemd timers
  .sync.yml
  files/vacuum_full_tables.sh
  lib/facter/pe_databases.rb
  manifests/collect.pp
  manifests/init.pp
  manifests/maintenance.pp
  manifests/maintenance/pg_repack.pp
  manifests/maintenance/vacuum_full.pp
  manifests/pg_repack.pp
  metadata.json
  spec/classes/init_spec.rb
  spec/classes/maintenance/pg_repack_spec.rb
  spec/classes/maintenance/vacuum_full_spec.rb
  spec/classes/maintenance_spec.rb
  spec/classes/pg_repack_spec.rb
  spec/default_facts.yml
  templates/service.epp
  templates/timer.epp
Labels: backwards-incompatible, enhancement

#69 PE Version and PDK Update
  .github/workflows/pe_latest_testing.yml
  .github/workflows/pe_lts_testing.yml
  .gitignore
  .pdkignore
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#73 Fix scope of disable_maintenance param
  .github/workflows/pe_latest_testing.yml
  .github/workflows/pe_lts_testing.yml
  .gitignore
  .pdkignore
  README.md
  manifests/backup.pp
  manifests/init.pp
  metadata.json
  spec/spec_helper.rb
Labels: bug

#74 Fix path in backup.pp and reset pgrepack schema task
  files/common.sh
  manifests/backup.pp
  tasks/reset_pgrepack_schema.sh
Labels: bug
